/* Header file generated by fdesign on Wed Jun 27 15:29:30 2012 */

#ifndef FD_lte_scope_h_
#define FD_lte_scope_h_

#include <forms.h>

/* Callbacks, globals and object handlers */

extern void RECAL_callback( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * lte_scope;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * channel_t_re;
    FL_OBJECT * scatter_plot;
    FL_OBJECT * demod_out;
    FL_OBJECT * channel_f;
    FL_OBJECT * channel_t_im;
    FL_OBJECT * decoder_input;
    FL_OBJECT * scatter_plot2;
    FL_OBJECT * scatter_plot1;
    FL_OBJECT * fig11;
    FL_OBJECT * fig12;
    FL_OBJECT * recal;
} FD_lte_scope;

extern FD_lte_scope * create_form_lte_scope( void );

#endif /* FD_lte_scope_h_ */
