/* Form definition file generated by fdesign */

#include <stdlib.h>
#include "lte_scope.h"


/***************************************
 ***************************************/

FD_lte_scope *
create_form_lte_scope( void )
{
    FL_OBJECT *obj;
    FD_lte_scope *fdui = fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->lte_scope = fl_bgn_form( FL_NO_BOX, 745, 633 );

    obj = fl_add_box( FL_ROUNDED_BOX, 0, 0, 745, 633, "" );
    fl_set_object_color( obj, FL_BLACK, FL_BLUE );

    fdui->fig12 = obj = fl_add_xyplot( FL_NORMAL_XYPLOT, 240, 0, 240, 160, "" );
    fl_set_object_boxtype( obj, FL_ROUNDED_BOX );
    fl_set_object_color( obj, FL_RIGHT_BCOL, FL_GREEN );

    fdui->fig22 = obj = fl_add_xyplot( FL_DOTDASHED_XYPLOT, 240, 320, 240, 160, "" );
    fl_set_object_boxtype( obj, FL_ROUNDED_BOX );
    fl_set_object_color( obj, FL_RIGHT_BCOL, FL_ORANGERED );

    fdui->fig11 = obj = fl_add_xyplot( FL_NORMAL_XYPLOT, 0, 0, 240, 160, "" );
    fl_set_object_boxtype( obj, FL_ROUNDED_BOX );
    fl_set_object_color( obj, FL_RIGHT_BCOL, FL_GREEN );

    fdui->fig21 = obj = fl_add_xyplot( FL_NORMAL_XYPLOT, 0, 320, 240, 160, "" );
    fl_set_object_boxtype( obj, FL_ROUNDED_BOX );
    fl_set_object_color( obj, FL_RIGHT_BCOL, FL_ORANGERED );

    fdui->fig13 = obj = fl_add_xyplot( FL_NORMAL_XYPLOT, 0, 160, 240, 160, "" );
    fl_set_object_boxtype( obj, FL_ROUNDED_BOX );
    fl_set_object_color( obj, FL_RIGHT_BCOL, FL_YELLOW );

    fdui->fig14 = obj = fl_add_xyplot( FL_NORMAL_XYPLOT, 240, 160, 240, 160, "" );
    fl_set_object_boxtype( obj, FL_ROUNDED_BOX );
    fl_set_object_color( obj, FL_RIGHT_BCOL, FL_YELLOW );

    fdui->fig24 = obj = fl_add_xyplot( FL_POINTS_XYPLOT, 490, 0, 250, 200, "" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_WHITE, FL_ORANGERED );

    fdui->ZFB = obj = fl_add_button( FL_NORMAL_BUTTON, 240, 490, 80, 30, "A-ZFB" );
    fl_set_object_boxtype( obj, FL_ROUNDED3D_UPBOX );
    fl_set_object_color( obj, FL_ORANGERED, FL_GREEN );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, ZFB_callback, 1 );

    fdui->ZFB1 = obj = fl_add_button( FL_NORMAL_BUTTON, 320, 490, 80, 30, "NO-ZFB" );
    fl_set_object_boxtype( obj, FL_ROUNDED3D_UPBOX );
    fl_set_object_color( obj, FL_ORANGERED, FL_GREEN );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, ZFB1_callback, 0 );

    fdui->fig23 = obj = fl_add_xyplot( FL_NORMAL_XYPLOT, 0, 480, 240, 150, "" );
    fl_set_object_boxtype( obj, FL_ROUNDED3D_UPBOX );
    fl_set_object_color( obj, FL_BLUE, FL_MAGENTA );

    obj = fl_add_button( FL_NORMAL_BUTTON, 320, 530, 80, 40, "EXIT" );
    fl_set_object_boxtype( obj, FL_ROUNDED3D_UPBOX );
    fl_set_object_color( obj, FL_LAWNGREEN, FL_RED );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, Exit_callback, 1 );

    obj = fl_add_button( FL_NORMAL_BUTTON, 310, 603, 70, 30, "RayL1" );
    fl_set_object_boxtype( obj, FL_ROUNDED3D_UPBOX );
    fl_set_object_color( obj, FL_LINEN, FL_GREEN );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, RayL1_callback, 1 );

    obj = fl_add_button( FL_NORMAL_BUTTON, 380, 603, 70, 30, "Rice8" );
    fl_set_object_boxtype( obj, FL_ROUNDED3D_UPBOX );
    fl_set_object_color( obj, FL_IVORY, FL_GREEN );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, Rice8_callback, 1 );

    fdui->SCM_C = obj = fl_add_button( FL_NORMAL_BUTTON, 240, 603, 70, 30, "SCM_C" );
    fl_set_object_boxtype( obj, FL_ROUNDED3D_UPBOX );
    fl_set_object_color( obj, FL_LAVENDERBLUSH, FL_GREEN );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, SCM_C_callback, 1 );

    obj = fl_add_button( FL_NORMAL_BUTTON, 240, 580, 210, 20, "Channel Model" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_IVORY, FL_GREEN );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, Rice8_callback, 1 );

    fdui->fig25 = obj = fl_add_xyplot( FL_POINTS_XYPLOT, 490, 210, 250, 200, "" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_WHITE, FL_FUCHSIA );

    fdui->fig26 = obj = fl_add_xyplot( FL_POINTS_XYPLOT, 490, 420, 250, 200, "" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_WHITE, FL_BLUE );

    obj = fl_add_button( FL_NORMAL_BUTTON, 400, 490, 80, 30, "RE-CAL" );
    fl_set_object_boxtype( obj, FL_ROUNDED3D_UPBOX );
    fl_set_object_color( obj, FL_ORANGERED, FL_GREEN );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_callback( obj, RECAL_callback, 0 );

    fl_end_form( );

    fdui->lte_scope->fdui = fdui;

    return fdui;
}
