/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "RRM-RRC-Definitions"
 * 	found in "/homes/gauthier/PROJETS/OPENAIR4G/openair2/RRM_4_RRC_LITE/src/com/asn1/rrc-rrm.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#ifndef	_E_NodeB_Identity_H_
#define	_E_NodeB_Identity_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PhysCellId.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* E-NodeB-Identity */
typedef struct E_NodeB_Identity {
	PhysCellId_t	 physCellId;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E_NodeB_Identity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E_NodeB_Identity;

#ifdef __cplusplus
}
#endif

#endif	/* _E_NodeB_Identity_H_ */
#include <asn_internal.h>
