/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "RRM-RRC-Definitions"
 * 	found in "/homes/gauthier/PROJETS/OPENAIR4G/openair2/RRM_4_RRC_LITE/src/com/asn1/rrc-rrm.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#ifndef	_RRC_RRM_MessageType_H_
#define	_RRC_RRM_MessageType_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RRCSystemConfigurationRequest.h"
#include "RRCAddUserRequest.h"
#include "RRCAddUserConfirm.h"
#include "RRCAddDataRadioBearerRequest.h"
#include "RRCAddDataRadioBearerConfirm.h"
#include "RRCRemoveUserRequest.h"
#include "RRCRemoveDataRadioBearerRequest.h"
#include "RRCRemoveDataRadioBearerConfirm.h"
#include "RRCUserReconfigurationComplete.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRC_RRM_MessageType_PR {
	RRC_RRM_MessageType_PR_NOTHING,	/* No components present */
	RRC_RRM_MessageType_PR_c1,
	RRC_RRM_MessageType_PR_messageClassExtension
} RRC_RRM_MessageType_PR;
typedef enum RRC_RRM_MessageType__c1_PR {
	RRC_RRM_MessageType__c1_PR_NOTHING,	/* No components present */
	RRC_RRM_MessageType__c1_PR_rrcSystemConfigurationRequest,
	RRC_RRM_MessageType__c1_PR_rrcAddUserRequest,
	RRC_RRM_MessageType__c1_PR_rrcAddUserConfirm,
	RRC_RRM_MessageType__c1_PR_rrcAddDataRadioBearerRequest,
	RRC_RRM_MessageType__c1_PR_rrcAddDataRadioBearerConfirm,
	RRC_RRM_MessageType__c1_PR_rrcRemoveUserRequest,
	RRC_RRM_MessageType__c1_PR_rrcRemoveDataRadioBearerRequest,
	RRC_RRM_MessageType__c1_PR_rrcRemoveDataRadioBearerConfirm,
	RRC_RRM_MessageType__c1_PR_rrcUserReconfigurationComplete
} RRC_RRM_MessageType__c1_PR;

/* RRC-RRM-MessageType */
typedef struct RRC_RRM_MessageType {
	RRC_RRM_MessageType_PR present;
	union RRC_RRM_MessageType_u {
		struct RRC_RRM_MessageType__c1 {
			RRC_RRM_MessageType__c1_PR present;
			union RRC_RRM_MessageType__c1_u {
				RRCSystemConfigurationRequest_t	 rrcSystemConfigurationRequest;
				RRCAddUserRequest_t	 rrcAddUserRequest;
				RRCAddUserConfirm_t	 rrcAddUserConfirm;
				RRCAddDataRadioBearerRequest_t	 rrcAddDataRadioBearerRequest;
				RRCAddDataRadioBearerConfirm_t	 rrcAddDataRadioBearerConfirm;
				RRCRemoveUserRequest_t	 rrcRemoveUserRequest;
				RRCRemoveDataRadioBearerRequest_t	 rrcRemoveDataRadioBearerRequest;
				RRCRemoveDataRadioBearerConfirm_t	 rrcRemoveDataRadioBearerConfirm;
				RRCUserReconfigurationComplete_t	 rrcUserReconfigurationComplete;
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} c1;
		struct RRC_RRM_MessageType__messageClassExtension {
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} messageClassExtension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRC_RRM_MessageType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRC_RRM_MessageType;

#ifdef __cplusplus
}
#endif

#endif	/* _RRC_RRM_MessageType_H_ */
#include <asn_internal.h>
