/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "RRM-RRC-Definitions"
 * 	found in "/homes/gauthier/PROJETS/OPENAIR4G/openair2/RRM_4_RRC_LITE/src/com/asn1/rrc-rrm.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#include "RRCAddDataRadioBearerRequest.h"

static asn_TYPE_member_t asn_MBR_RRCAddDataRadioBearerRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRCAddDataRadioBearerRequest, transactionId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransactionId,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"transactionId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRCAddDataRadioBearerRequest, e_NodeB_Identity),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E_NodeB_Identity,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"e-NodeB-Identity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRCAddDataRadioBearerRequest, c_RNTI),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OpenAir_C_RNTI,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"c-RNTI"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRCAddDataRadioBearerRequest, drb_Identity),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DRB_Identity,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"drb-Identity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRCAddDataRadioBearerRequest, applicationTrafficClass),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OpenAir_Application_TrafficClass,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"applicationTrafficClass"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRCAddDataRadioBearerRequest, applicationPacketDelay),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OpenAir_Application_ms_PacketDelay,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"applicationPacketDelay"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRCAddDataRadioBearerRequest, guaranted_bit_rate_uplink),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OpenAir_ApplicationKBitRate,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"guaranted-bit-rate-uplink"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRCAddDataRadioBearerRequest, max_bit_rate_uplink),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OpenAir_ApplicationKBitRate,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"max-bit-rate-uplink"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRCAddDataRadioBearerRequest, guaranted_bit_rate_downlink),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OpenAir_ApplicationKBitRate,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"guaranted-bit-rate-downlink"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRCAddDataRadioBearerRequest, max_bit_rate_downlink),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OpenAir_ApplicationKBitRate,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"max-bit-rate-downlink"
		},
};
static ber_tlv_tag_t asn_DEF_RRCAddDataRadioBearerRequest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_RRCAddDataRadioBearerRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* transactionId at 54 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* e-NodeB-Identity at 55 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* c-RNTI at 56 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* drb-Identity at 57 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* applicationTrafficClass at 58 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* applicationPacketDelay at 59 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* guaranted-bit-rate-uplink at 60 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* max-bit-rate-uplink at 61 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* guaranted-bit-rate-downlink at 62 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 } /* max-bit-rate-downlink at 64 */
};
static asn_SEQUENCE_specifics_t asn_SPC_RRCAddDataRadioBearerRequest_specs_1 = {
	sizeof(struct RRCAddDataRadioBearerRequest),
	offsetof(struct RRCAddDataRadioBearerRequest, _asn_ctx),
	asn_MAP_RRCAddDataRadioBearerRequest_tag2el_1,
	10,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_RRCAddDataRadioBearerRequest = {
	"RRCAddDataRadioBearerRequest",
	"RRCAddDataRadioBearerRequest",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RRCAddDataRadioBearerRequest_tags_1,
	sizeof(asn_DEF_RRCAddDataRadioBearerRequest_tags_1)
		/sizeof(asn_DEF_RRCAddDataRadioBearerRequest_tags_1[0]), /* 1 */
	asn_DEF_RRCAddDataRadioBearerRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_RRCAddDataRadioBearerRequest_tags_1)
		/sizeof(asn_DEF_RRCAddDataRadioBearerRequest_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_RRCAddDataRadioBearerRequest_1,
	10,	/* Elements count */
	&asn_SPC_RRCAddDataRadioBearerRequest_specs_1	/* Additional specs */
};

