/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "RRM-RRC-Definitions"
 * 	found in "/homes/gauthier/PROJETS/OPENAIR4G/openair2/RRM_4_RRC_LITE/src/com/asn1/rrc-rrm.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#include "RRCRemoveDataRadioBearerConfirm.h"

static asn_TYPE_member_t asn_MBR_RRCRemoveDataRadioBearerConfirm_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRCRemoveDataRadioBearerConfirm, transactionId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransactionId,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"transactionId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRCRemoveDataRadioBearerConfirm, e_NodeB_Identity),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E_NodeB_Identity,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"e-NodeB-Identity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRCRemoveDataRadioBearerConfirm, c_RNTI),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OpenAir_C_RNTI,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"c-RNTI"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRCRemoveDataRadioBearerConfirm, drb_Identity),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DRB_Identity,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"drb-Identity"
		},
};
static ber_tlv_tag_t asn_DEF_RRCRemoveDataRadioBearerConfirm_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_RRCRemoveDataRadioBearerConfirm_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* transactionId at 88 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* e-NodeB-Identity at 89 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* c-RNTI at 90 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* drb-Identity at 92 */
};
static asn_SEQUENCE_specifics_t asn_SPC_RRCRemoveDataRadioBearerConfirm_specs_1 = {
	sizeof(struct RRCRemoveDataRadioBearerConfirm),
	offsetof(struct RRCRemoveDataRadioBearerConfirm, _asn_ctx),
	asn_MAP_RRCRemoveDataRadioBearerConfirm_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_RRCRemoveDataRadioBearerConfirm = {
	"RRCRemoveDataRadioBearerConfirm",
	"RRCRemoveDataRadioBearerConfirm",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RRCRemoveDataRadioBearerConfirm_tags_1,
	sizeof(asn_DEF_RRCRemoveDataRadioBearerConfirm_tags_1)
		/sizeof(asn_DEF_RRCRemoveDataRadioBearerConfirm_tags_1[0]), /* 1 */
	asn_DEF_RRCRemoveDataRadioBearerConfirm_tags_1,	/* Same as above */
	sizeof(asn_DEF_RRCRemoveDataRadioBearerConfirm_tags_1)
		/sizeof(asn_DEF_RRCRemoveDataRadioBearerConfirm_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_RRCRemoveDataRadioBearerConfirm_1,
	4,	/* Elements count */
	&asn_SPC_RRCRemoveDataRadioBearerConfirm_specs_1	/* Additional specs */
};

