/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "RRM-RRC-Definitions"
 * 	found in "/homes/gauthier/PROJETS/OPENAIR4G/openair2/RRM_4_RRC_LITE/src/com/asn1/rrc-rrm.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#ifndef	_RRCSystemConfigurationResponse_H_
#define	_RRCSystemConfigurationResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransactionId.h"
#include "OpenAir-RRM-Response-Status.h"
#include "OpenAir-RRM-Response-Reason.h"
#include "E-NodeB-Identity.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SystemInformationBlockType1;
struct SystemInformation;

/* RRCSystemConfigurationResponse */
typedef struct RRCSystemConfigurationResponse {
	TransactionId_t	 transactionId;
	OpenAir_RRM_Response_Status_t	 rrm_Response_Status;
	OpenAir_RRM_Response_Reason_t	 rrm_Response_Reason;
	E_NodeB_Identity_t	 e_NodeB_Identity;
	struct SystemInformationBlockType1	*systemInformationBlockType1	/* OPTIONAL */;
	struct SystemInformation	*systemInformation	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCSystemConfigurationResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCSystemConfigurationResponse;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SystemInformationBlockType1.h"
#include "SystemInformation.h"

#endif	/* _RRCSystemConfigurationResponse_H_ */
#include <asn_internal.h>
