/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "RRM-RRC-Definitions"
 * 	found in "/homes/gauthier/PROJETS/OPENAIR4G/openair2/RRM_4_RRC_LITE/src/com/asn1/rrc-rrm.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#ifndef	_TransactionId_H_
#define	_TransactionId_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TransactionId */
typedef long	 TransactionId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TransactionId;
asn_struct_free_f TransactionId_free;
asn_struct_print_f TransactionId_print;
asn_constr_check_f TransactionId_constraint;
ber_type_decoder_f TransactionId_decode_ber;
der_type_encoder_f TransactionId_encode_der;
xer_type_decoder_f TransactionId_decode_xer;
xer_type_encoder_f TransactionId_encode_xer;
per_type_decoder_f TransactionId_decode_uper;
per_type_encoder_f TransactionId_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TransactionId_H_ */
#include <asn_internal.h>
