#!/bin/sh
echo "Bringup UE interface"
rmmod nasmesh
make naslite_netlink_ether oaisim
insmod  $OPENAIR2_DIR/NAS/DRIVER/LITE/nasmesh.ko nas_IMEI=3,9,1,8,3,6,7,3,0,0,0,0,0,0

#avoid conflict with reserved multicast addresses (224.0.0.11,224.0.0.13, 224.0.0.16)
ip addr add dev eth1 192.168.14.1/24 broadcast 192.168.14.255
ip link set oai0 broadcast ff:ff:ff:ff:ff:ff
ip route add 192.168.14.0/24 dev eth1
ip route add 224.0.0.160/28 dev eth1
ip link set oai0 up
sleep 1
ifconfig oai0 10.0.1.2 netmask 255.255.255.0 broadcast 10.0.1.255
sleep 1
ip addr add dev oai0 2001:1::2/64
# -a     -> Add RB
# -d    -> Delete RB
# -cxx  -> lcr
# -ixx  -> instance
# -zxx  -> dscp
# -fxxx -> classref (uid of a classifier entry) if fn is used , fn is used for send classifier and n+1 for receive classifier
# -sxxx -> source ipv4 address
# -txxx -> destination ipv4 address
# -x    -> source ipv6 address
# -y    -> destination ipv6 address
# -r    -> radio bearer id
$OPENAIR2_DIR/NAS/DRIVER/LITE/RB_TOOL/rb_tool -a -c0 -f0 -i0 -z0  -x 2001:1::2 -y 2001:1::1 -r 3
$OPENAIR2_DIR/NAS/DRIVER/LITE/RB_TOOL/rb_tool -a -c0 -f2 -i0 -z64 -s 10.0.1.2/32  -t 10.0.1.1/32  -r 3
sleep 1
echo "to see UE stats, pleasae run : watch_ue script"
echo "$OPENAIR_TARGETS/SIMU/USER/oaisim  -b0 -M1 -p2  > /dev/null"
nice -10 $OPENAIR_TARGETS/SIMU/USER/oaisim  -b0 -M1 -p2 -g3 -l3 > /dev/null
echo "End"
