/* Header file generated by fdesign on Wed May 16 15:03:13 2012 */

#ifndef FD_lte_scope_h_
#define FD_lte_scope_h_

#include <forms.h>

/* Callbacks, globals and object handlers */

extern void ZFB_callback( FL_OBJECT *, long );
extern void ZFB1_callback( FL_OBJECT *, long );
extern void Exit_callback( FL_OBJECT *, long );
extern void RayL1_callback( FL_OBJECT *, long );
extern void Rice8_callback( FL_OBJECT *, long );
extern void SCM_C_callback( FL_OBJECT *, long );
extern void RECAL_callback( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * lte_scope;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * fig12;
    FL_OBJECT * fig22;
    FL_OBJECT * fig11;
    FL_OBJECT * fig21;
    FL_OBJECT * fig13;
    FL_OBJECT * fig14;
    FL_OBJECT * fig24;
    FL_OBJECT * ZFB;
    FL_OBJECT * ZFB1;
    FL_OBJECT * fig23;
    FL_OBJECT * SCM_C;
    FL_OBJECT * fig25;
    FL_OBJECT * fig26;
} FD_lte_scope;

extern FD_lte_scope * create_form_lte_scope( void );

#endif /* FD_lte_scope_h_ */
