/* Header file generated by fdesign on Tue Feb 26 18:12:07 2013 */

#ifndef FD_stats_form_h_
#define FD_stats_form_h_

#include <forms.h>

/* Callbacks, globals and object handlers */



/* Forms and Objects */

typedef struct {
    FL_FORM   * stats_form;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * stats_text;
} FD_stats_form;

extern FD_stats_form * create_form_stats_form( void );

#endif /* FD_stats_form_h_ */
