include $(OPENAIR1_DIR)/SIMULATION/LTE_PHY/Makefile

CFLAGS += -DMEX

# Just compile all the PHY objects
OBJ = $(PHY_OBJS) $(TOP_DIR)/SIMULATION/TOOLS/taus.o

# List of all mex-files to compile
MEX_FILES = /homes/wagner/Dev/trunk/openair1/MATLAB/PHY/LTE_TRANSPORT/mexfiles/qam16_qam16_mu_mimo.mexglx
MEX_FILES += /homes/wagner/Dev/trunk/openair1/MATLAB/PHY/LTE_TRANSPORT/mexfiles/get_tbs.mexglx
MEX_FILES += /homes/wagner/Dev/trunk/openair1/MATLAB/PHY/LTE_TRANSPORT/mexfiles/dlsch_encoding.mexglx
MEX_FILES += /homes/wagner/Dev/trunk/openair1/MATLAB/PHY/LTE_TRANSPORT/mexfiles/dlsch_decoding.mexglx
MEX_FILES += /homes/wagner/Dev/trunk/openair1/MATLAB/PHY/LTE_TRANSPORT/mexfiles/dlsch_channel_level_prec.mexglx
MEX_FILES += /homes/wagner/Dev/trunk/openair1/MATLAB/PHY/LTE_TRANSPORT/mexfiles/dlsch_channel_compensation_prec.mexglx
MEX_FILES += /homes/wagner/Dev/trunk/openair1/MATLAB/PHY/LTE_TRANSPORT/mexfiles/dlsch_dual_stream_correlation.mexglx
MEX_FILES += /homes/wagner/Dev/trunk/openair1/MATLAB/PHY/LTE_TRANSPORT/mexfiles/dlsch_detection_mrc.mexglx
MEX_FILES += /homes/wagner/Dev/trunk/openair1/MATLAB/PHY/LTE_TRANSPORT/mexfiles/dlsch_mu_mimo_llr.mexglx
MEX_FILES += /homes/wagner/Dev/trunk/openair1/MATLAB/PHY/LTE_TRANSPORT/mexfiles/dlsch_su_mimo_llr.mexglx
MEX_FILES += /homes/wagner/Dev/trunk/openair1/MATLAB/PHY/TOOLS/mexfiles/log2_approx.mexglx
MEX_FILES += /homes/wagner/Dev/trunk/openair1/MATLAB/SIMULATION/TOOLS/mexfiles/taus.mexglx
MEX_FILES += /homes/wagner/Dev/trunk/openair1/MATLAB/SIMULATION/TOOLS/mexfiles/set_taus_seed.mexglx

OCT_FILES = /homes/wagner/Dev/trunk/openair1/MATLAB/PHY/LTE_TRANSPORT/mexfiles/qam16_qam16_mu_mimo.oct
OCT_FILES += /homes/wagner/Dev/trunk/openair1/MATLAB/PHY/LTE_TRANSPORT/mexfiles/get_tbs.oct
OCT_FILES += /homes/wagner/Dev/trunk/openair1/MATLAB/PHY/LTE_TRANSPORT/mexfiles/dlsch_encoding.oct
OCT_FILES += /homes/wagner/Dev/trunk/openair1/MATLAB/PHY/LTE_TRANSPORT/mexfiles/dlsch_decoding.oct
OCT_FILES += /homes/wagner/Dev/trunk/openair1/MATLAB/PHY/LTE_TRANSPORT/mexfiles/dlsch_channel_level_prec.oct
OCT_FILES += /homes/wagner/Dev/trunk/openair1/MATLAB/PHY/LTE_TRANSPORT/mexfiles/dlsch_channel_compensation_prec.oct
OCT_FILES += /homes/wagner/Dev/trunk/openair1/MATLAB/PHY/LTE_TRANSPORT/mexfiles/dlsch_dual_stream_correlation.oct
OCT_FILES += /homes/wagner/Dev/trunk/openair1/MATLAB/PHY/LTE_TRANSPORT/mexfiles/dlsch_detection_mrc.oct
OCT_FILES += /homes/wagner/Dev/trunk/openair1/MATLAB/PHY/LTE_TRANSPORT/mexfiles/dlsch_mu_mimo_llr.oct
OCT_FILES += /homes/wagner/Dev/trunk/openair1/MATLAB/PHY/LTE_TRANSPORT/mexfiles/dlsch_su_mimo_llr.oct
OCT_FILES += /homes/wagner/Dev/trunk/openair1/MATLAB/PHY/TOOLS/mexfiles/log2_approx.oct
OCT_FILES += /homes/wagner/Dev/trunk/openair1/MATLAB/SIMULATION/TOOLS/mexfiles/taus.oct
OCT_FILES += /homes/wagner/Dev/trunk/openair1/MATLAB/SIMULATION/TOOLS/mexfiles/set_taus_seed.oct

# ===========================================================================================
# Commands to compile the static and shared lib for mex-files

# Libpath
LIBDIR := ./lib
LIBNAME := oai

sharedlib : $(OBJ)
	@$(CC) -shared -Wl,-soname,lib$(LIBNAME).so.1 -o $(LIBDIR)/lib$(LIBNAME).so.1.0.1 $(OBJ) -lc

mytest :
	@echo $(OBJ)

staticlib : $(OBJ)
	@ar ruv $(LIBDIR)/lib$(LIBNAME).a $(OBJ)

libs : $(OBJ)
	@$(CC) -shared -Wl,-soname,lib$(LIBNAME).so.1 -o $(LIBDIR)/lib$(LIBNAME).so.1.0.1 $(OBJ) -lc
	@ar ruv $(LIBDIR)/lib$(LIBNAME).a $(OBJ)

$(MEX_FILES) : %.mexglx : %.c
	@echo 
	@echo Compiling $< ...
#	@mex -g CFLAGS="$(CFLAGS)" -l$(LIBNAME) -L$(LIBDIR) -output $@ $<
#	@mkoctfile --mex -o $@ CFLAGS="\$CFLAGS" -l$(LIBNAME) -L$(LIBDIR) $<
#	@mex -g CFLAGS="$(CFLAGS)" -l$(OBJ) -output $@ $<
#        @mkoctfile --mex -g -o $@ CFLAGS="\$CFLAGS" -lm $(OBJ)  $<
        @mkoctfile --mex  CFLAGS="\$CFLAGS" -l$(LIBNAME) -L$(LIBDIR) -o $@ $<
#        @mkoctfile -o $@ CFLAGS="\$CFLAGS" -lm $(OBJ)  $<

mex : $(MEX_FILES)

oct_test : 
	mkoctfile CFLAGS='\$CFLAGS' -l$(LIBNAME) -L$(LIBDIR) /homes/wagner/Dev/trunk/openair1/MATLAB/PHY/LTE_TRANSPORT/mexfiles/qam16_qam16_mu_mimo.c -o test.oct

$(OCT_FILES) : %.oct : %.c
	@echo
	@echo Compiling $< ...
#        @mkoctfile --mex -g -o $@ CFLAGS="\$CFLAGS" -lm $(OBJ)  $<
        @mkoctfile CFLAGS="\$CFLAGS" -l$(LIBNAME) -L$(LIBDIR) -o $@ $<
#        @mkoctfile -o $@ CFLAGS="\$CFLAGS" -lm $(OBJ)  $<

oct : $(OCT_FILES)

cleanlibs :
	rm $(LIBDIR)/lib$(LIBNAME).*

cleanmex :
	rm -f $(MEX_FILES)
