NUMBER_OF_OFDM_CARRIERS_EMOS = 512; 
NUMBER_OF_USEFUL_CARRIERS_EMOS = 300;

N_RB_DL_EMOS = 25;
N_PILOTS_PER_RB = 4;
N_SLOTS_EMOS = 2;

N_RB_UL_EMOS = 25;
N_PILOTS_PER_RB_UL = 12;
N_SRS_SYMBOLS = 5;

MAX_DCI_PER_FRAME = 20;
MAX_UCI_PER_FRAME = 20;

PBCH_PDU_SIZE = 6;

NUMBER_OF_eNB_MAX = 3;
NUMBER_OF_UE_MAX = 1;
NUMBER_OF_SUBBANDS = 7;

NB_ANTENNAS_RX = 2;
NB_ANTENNAS_TX = 2;


%phy_measurements_struct = struct([]);
%dci_alloc_t = struct([]);
phy_measurements_struct = struct('field',uint32(0));
dci_alloc_t = struct('field',uint32(0));

fifo_dump_emos_struct_UE = struct(...
    'timestamp',int64(0),...
    'frame_tx',uint32(0),...
    'frame_rx',uint32(0),...
    'phy_measurements', repmat(phy_measurements_struct,1,20),... 
    'pbch_pdu',uint8(zeros(NUMBER_OF_eNB_MAX,PBCH_PDU_SIZE)),...
    'pdu_errors',uint32(zeros(1,NUMBER_OF_eNB_MAX)),...
    'pdu_errors_last',uint32(zeros(1,NUMBER_OF_eNB_MAX)),...
    'pdu_errors_conseq',uint32(zeros(1,NUMBER_OF_eNB_MAX)),...
    'pdu_fer',uint32(zeros(1,NUMBER_OF_eNB_MAX)),...
    'dci_alloc',repmat(dci_alloc_t,2,10),...
    'timing_offset',int32(0),...
    'timing_advance',int32(0),...
    'freq_offset',int32(0),...
    'rx_total_gain_dB',uint32(0),...
    'mimo_mode',uint8(0),...
    'channel',int32(zeros(NUMBER_OF_eNB_MAX,NB_ANTENNAS_RX*NB_ANTENNAS_TX,N_RB_DL_EMOS*N_PILOTS_PER_RB*N_SLOTS_EMOS)));

