oaisim: 
	(cd $(OPENAIR_TARGETS)/SIMU/USER && make)
nasmesh:
	(cd $(OPENAIR2_DIR)/NAS/DRIVER/MESH/ && make)
	(cd $(OPENAIR2_DIR)/NAS/DRIVER/MESH/RB_TOOL/rb_tool && make)

one_eNB_two_UE: oaisim nasmesh
