#!/bin/sh
echo "Bringup UE interface"
sudo pkill oaisim
sudo pkill oaisim
sudo /sbin/rmmod nasmesh
sudo make naslite_netlink_ether oaisim
sudo insmod  $OPENAIR2_DIR/NAS/DRIVER/LITE/nasmesh.ko  nas_IMEI=3,9,1,8,3,6,7,3,0,0,0,0,0,0

#avoid conflict with reserved multicast addresses (224.0.0.11,224.0.0.13, 224.0.0.16)
#sudo route add -net 224.0.0.0 netmask 240.0.0.0 dev eth0
sudo ip link set oai0 broadcast ff:ff:ff:ff:ff:ff
sudo ip route add 239.0.0.160/28 dev eth1
#sudo ip link set oai0 up
sleep 1
#IPv4 NO MORE NEEDED sudo ifconfig oai0 10.0.1.2 netmask 255.255.255.0 broadcast 10.0.1.255
#IPv4 NO MORE NEEDED sleep 1
#LG TEST sudo ip addr add dev oai0 2001:1::2/64
# -a     -> Add RB
# -d    -> Delete RB
# -cxx  -> lcr
# -ixx  -> instance
# -zxx  -> dscp
# -fxxx -> classref (uid of a classifier entry) if fn is used , fn is used for send classifier and n+1 for receive classifier
# -sxxx -> source ipv4 address
# -txxx -> destination ipv4 address
# -x    -> source ipv6 address
# -y    -> destination ipv6 address
# -r    -> radio bearer id
# commented to try add classification rule for RS FF02::2 $OPENAIR2_DIR/NAS/DRIVER/LITE/RB_TOOL/rb_tool -a -c0 -f0 -i0 -z0  -x 2001:1::2 -y 2001:1::1 -r 3
$OPENAIR2_DIR/NAS/DRIVER/LITE/RB_TOOL/rb_tool -a -c0 -f0 -i0 -z0  -x 0::0/128 -y 0::0/128 -r 3
#IPv4 NO MORE NEEDED $OPENAIR2_DIR/NAS/DRIVER/LITE/RB_TOOL/rb_tool -a -c0 -f2 -i0 -z64 -s 10.0.1.2/32  -t 10.0.1.1/32  -r 3
echo "to see UE stats, pleasae run : watch_ue script"
echo "$OPENAIR_TARGETS/SIMU/USER/oaisim  -b0 -M1 -p2  > /dev/null"
#sudo nice -10 $OPENAIR_TARGETS/SIMU/USER/oaisim  -b0 -M1 -p2 -g3 -l3 > /dev/null
nice -20 $OPENAIR_TARGETS/SIMU/USER/oaisim -E 1234 -b0 -M1 -p2 -g3 -l3 > /dev/null
#nice -20 $OPENAIR_TARGETS/SIMU/USER/oaisim -E 1234 -b0 -M1 -p2 -g3 -l7

#nice -10 $OPENAIR_TARGETS/SIMU/USER/oaisim -E 1234 -b0 -M1 -p2 -g3 -l3 
echo "End"
