/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "RRM-RRC-Definitions"
 * 	found in "/homes/gauthier/PROJETS/OPENAIR4G/openair2/RRM_4_RRC_LITE/src/com/asn1/rrc-rrm.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#ifndef	_OpenAir_RRM_Response_Reason_H_
#define	_OpenAir_RRM_Response_Reason_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum OpenAir_RRM_Response_Reason {
	OpenAir_RRM_Response_Reason_ok	= 0,
	OpenAir_RRM_Response_Reason_protocolError	= 1,
	OpenAir_RRM_Response_Reason_ressourcesUnavailable	= 2,
	OpenAir_RRM_Response_Reason_malformedMessage	= 3,
	OpenAir_RRM_Response_Reason_unknownMessage	= 4,
	OpenAir_RRM_Response_Reason_internalError	= 5
} e_OpenAir_RRM_Response_Reason;

/* OpenAir-RRM-Response-Reason */
typedef long	 OpenAir_RRM_Response_Reason_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OpenAir_RRM_Response_Reason;
asn_struct_free_f OpenAir_RRM_Response_Reason_free;
asn_struct_print_f OpenAir_RRM_Response_Reason_print;
asn_constr_check_f OpenAir_RRM_Response_Reason_constraint;
ber_type_decoder_f OpenAir_RRM_Response_Reason_decode_ber;
der_type_encoder_f OpenAir_RRM_Response_Reason_encode_der;
xer_type_decoder_f OpenAir_RRM_Response_Reason_decode_xer;
xer_type_encoder_f OpenAir_RRM_Response_Reason_encode_xer;
per_type_decoder_f OpenAir_RRM_Response_Reason_decode_uper;
per_type_encoder_f OpenAir_RRM_Response_Reason_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _OpenAir_RRM_Response_Reason_H_ */
#include <asn_internal.h>
