/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "RRM-RRC-Definitions"
 * 	found in "/homes/gauthier/PROJETS/OPENAIR4G/openair2/RRM_4_RRC_LITE/src/com/asn1/rrc-rrm.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#ifndef	_OpenAir_ApplicationKBitRate_H_
#define	_OpenAir_ApplicationKBitRate_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* OpenAir-ApplicationKBitRate */
typedef long	 OpenAir_ApplicationKBitRate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OpenAir_ApplicationKBitRate;
asn_struct_free_f OpenAir_ApplicationKBitRate_free;
asn_struct_print_f OpenAir_ApplicationKBitRate_print;
asn_constr_check_f OpenAir_ApplicationKBitRate_constraint;
ber_type_decoder_f OpenAir_ApplicationKBitRate_decode_ber;
der_type_encoder_f OpenAir_ApplicationKBitRate_encode_der;
xer_type_decoder_f OpenAir_ApplicationKBitRate_decode_xer;
xer_type_encoder_f OpenAir_ApplicationKBitRate_encode_xer;
per_type_decoder_f OpenAir_ApplicationKBitRate_decode_uper;
per_type_encoder_f OpenAir_ApplicationKBitRate_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _OpenAir_ApplicationKBitRate_H_ */
#include <asn_internal.h>
