/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "RRM-RRC-Definitions"
 * 	found in "/homes/gauthier/PROJETS/OPENAIR4G/openair2/RRM_4_RRC_LITE/src/com/asn1/rrc-rrm.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#ifndef	_OpenAir_RRM_Response_Status_H_
#define	_OpenAir_RRM_Response_Status_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum OpenAir_RRM_Response_Status {
	OpenAir_RRM_Response_Status_success	= 0,
	OpenAir_RRM_Response_Status_warning	= 1,
	OpenAir_RRM_Response_Status_failure	= 2
} e_OpenAir_RRM_Response_Status;

/* OpenAir-RRM-Response-Status */
typedef long	 OpenAir_RRM_Response_Status_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OpenAir_RRM_Response_Status;
asn_struct_free_f OpenAir_RRM_Response_Status_free;
asn_struct_print_f OpenAir_RRM_Response_Status_print;
asn_constr_check_f OpenAir_RRM_Response_Status_constraint;
ber_type_decoder_f OpenAir_RRM_Response_Status_decode_ber;
der_type_encoder_f OpenAir_RRM_Response_Status_encode_der;
xer_type_decoder_f OpenAir_RRM_Response_Status_decode_xer;
xer_type_encoder_f OpenAir_RRM_Response_Status_encode_xer;
per_type_decoder_f OpenAir_RRM_Response_Status_decode_uper;
per_type_encoder_f OpenAir_RRM_Response_Status_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _OpenAir_RRM_Response_Status_H_ */
#include <asn_internal.h>
