/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "RRM-RRC-Definitions"
 * 	found in "/homes/gauthier/PROJETS/OPENAIR4G/openair2/RRM_4_RRC_LITE/src/com/asn1/rrc-rrm.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#include "RRC-RRM-MessageType.h"

static asn_per_constraints_t asn_PER_type_c1_constr_2 = {
	{ APC_CONSTRAINED,	 4,  4,  0,  8 }	/* (0..8) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_RRC_RRM_MessageType_constr_1 = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_c1_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRC_RRM_MessageType__c1, choice.rrcSystemConfigurationRequest),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCSystemConfigurationRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcSystemConfigurationRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRC_RRM_MessageType__c1, choice.rrcAddUserRequest),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCAddUserRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcAddUserRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRC_RRM_MessageType__c1, choice.rrcAddUserConfirm),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCAddUserConfirm,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcAddUserConfirm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRC_RRM_MessageType__c1, choice.rrcAddDataRadioBearerRequest),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCAddDataRadioBearerRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcAddDataRadioBearerRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRC_RRM_MessageType__c1, choice.rrcAddDataRadioBearerConfirm),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCAddDataRadioBearerConfirm,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcAddDataRadioBearerConfirm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRC_RRM_MessageType__c1, choice.rrcRemoveUserRequest),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCRemoveUserRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcRemoveUserRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRC_RRM_MessageType__c1, choice.rrcRemoveDataRadioBearerRequest),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCRemoveDataRadioBearerRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcRemoveDataRadioBearerRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRC_RRM_MessageType__c1, choice.rrcRemoveDataRadioBearerConfirm),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCRemoveDataRadioBearerConfirm,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcRemoveDataRadioBearerConfirm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRC_RRM_MessageType__c1, choice.rrcUserReconfigurationComplete),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCUserReconfigurationComplete,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcUserReconfigurationComplete"
		},
};
static asn_TYPE_tag2member_t asn_MAP_c1_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcSystemConfigurationRequest at 21 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rrcAddUserRequest at 22 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* rrcAddUserConfirm at 23 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* rrcAddDataRadioBearerRequest at 24 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* rrcAddDataRadioBearerConfirm at 25 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* rrcRemoveUserRequest at 26 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* rrcRemoveDataRadioBearerRequest at 27 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* rrcRemoveDataRadioBearerConfirm at 28 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 } /* rrcUserReconfigurationComplete at 31 */
};
static asn_CHOICE_specifics_t asn_SPC_c1_specs_2 = {
	sizeof(struct RRC_RRM_MessageType__c1),
	offsetof(struct RRC_RRM_MessageType__c1, _asn_ctx),
	offsetof(struct RRC_RRM_MessageType__c1, present),
	sizeof(((struct RRC_RRM_MessageType__c1 *)0)->present),
	asn_MAP_c1_tag2el_2,
	9,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_c1_2 = {
	"c1",
	"c1",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_c1_constr_2,
	asn_MBR_c1_2,
	9,	/* Elements count */
	&asn_SPC_c1_specs_2	/* Additional specs */
};

static ber_tlv_tag_t asn_DEF_messageClassExtension_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_messageClassExtension_specs_12 = {
	sizeof(struct RRC_RRM_MessageType__messageClassExtension),
	offsetof(struct RRC_RRM_MessageType__messageClassExtension, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_messageClassExtension_12 = {
	"messageClassExtension",
	"messageClassExtension",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_messageClassExtension_tags_12,
	sizeof(asn_DEF_messageClassExtension_tags_12)
		/sizeof(asn_DEF_messageClassExtension_tags_12[0]) - 1, /* 1 */
	asn_DEF_messageClassExtension_tags_12,	/* Same as above */
	sizeof(asn_DEF_messageClassExtension_tags_12)
		/sizeof(asn_DEF_messageClassExtension_tags_12[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_messageClassExtension_specs_12	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_RRC_RRM_MessageType_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRC_RRM_MessageType, choice.c1),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_c1_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"c1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRC_RRM_MessageType, choice.messageClassExtension),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_messageClassExtension_12,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"messageClassExtension"
		},
};
static asn_TYPE_tag2member_t asn_MAP_RRC_RRM_MessageType_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* c1 at 21 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* messageClassExtension at 32 */
};
static asn_CHOICE_specifics_t asn_SPC_RRC_RRM_MessageType_specs_1 = {
	sizeof(struct RRC_RRM_MessageType),
	offsetof(struct RRC_RRM_MessageType, _asn_ctx),
	offsetof(struct RRC_RRM_MessageType, present),
	sizeof(((struct RRC_RRM_MessageType *)0)->present),
	asn_MAP_RRC_RRM_MessageType_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_RRC_RRM_MessageType = {
	"RRC-RRM-MessageType",
	"RRC-RRM-MessageType",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_RRC_RRM_MessageType_constr_1,
	asn_MBR_RRC_RRM_MessageType_1,
	2,	/* Elements count */
	&asn_SPC_RRC_RRM_MessageType_specs_1	/* Additional specs */
};

