/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "RRM-RRC-Definitions"
 * 	found in "/homes/gauthier/PROJETS/OPENAIR4G/openair2/RRM_4_RRC_LITE/src/com/asn1/rrc-rrm.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#ifndef	_RRCAddDataRadioBearerRequest_H_
#define	_RRCAddDataRadioBearerRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransactionId.h"
#include "E-NodeB-Identity.h"
#include "OpenAir-C-RNTI.h"
#include "DRB-Identity.h"
#include "OpenAir-Application-TrafficClass.h"
#include "OpenAir-Application-ms-PacketDelay.h"
#include "OpenAir-ApplicationKBitRate.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RRCAddDataRadioBearerRequest */
typedef struct RRCAddDataRadioBearerRequest {
	TransactionId_t	 transactionId;
	E_NodeB_Identity_t	 e_NodeB_Identity;
	OpenAir_C_RNTI_t	 c_RNTI;
	DRB_Identity_t	 drb_Identity;
	OpenAir_Application_TrafficClass_t	 applicationTrafficClass;
	OpenAir_Application_ms_PacketDelay_t	 applicationPacketDelay;
	OpenAir_ApplicationKBitRate_t	 guaranted_bit_rate_uplink;
	OpenAir_ApplicationKBitRate_t	 max_bit_rate_uplink;
	OpenAir_ApplicationKBitRate_t	 guaranted_bit_rate_downlink;
	OpenAir_ApplicationKBitRate_t	 max_bit_rate_downlink;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCAddDataRadioBearerRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCAddDataRadioBearerRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _RRCAddDataRadioBearerRequest_H_ */
#include <asn_internal.h>
