/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "RRM-RRC-Definitions"
 * 	found in "/homes/gauthier/PROJETS/OPENAIR4G/openair2/RRM_4_RRC_LITE/src/com/asn1/rrc-rrm.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#ifndef	_RRCUserReconfigurationComplete_H_
#define	_RRCUserReconfigurationComplete_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransactionId.h"
#include "E-NodeB-Identity.h"
#include "OpenAir-C-RNTI.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RRCUserReconfigurationComplete */
typedef struct RRCUserReconfigurationComplete {
	TransactionId_t	 transactionId;
	E_NodeB_Identity_t	 e_NodeB_Identity;
	OpenAir_C_RNTI_t	 c_RNTI;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCUserReconfigurationComplete_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCUserReconfigurationComplete;

#ifdef __cplusplus
}
#endif

#endif	/* _RRCUserReconfigurationComplete_H_ */
#include <asn_internal.h>
