
/* A Bison parser, made by GNU Bison 2.4.1.  */

/* Skeleton interface for Bison's Yacc-like parsers in C
   
      Copyright (C) 1984, 1989, 1990, 2000, 2001, 2002, 2003, 2004, 2005, 2006
   Free Software Foundation, Inc.
   
   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.
   
   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.
   
   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.
   
   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */


/* Tokens.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
   /* Put the tokens into the symbol table, so that GDB and other debuggers
      know about them.  */
   enum yytokentype {
     QSTRING = 258,
     ADDR = 259,
     MACADDR = 260,
     BOOL = 261,
     NUMBER = 262,
     DECIMAL = 263,
     NUMPAIR = 264,
     MIP6ENTITY = 265,
     DEBUGLEVEL = 266,
     DEBUGLOGFILE = 267,
     DOROUTEOPTIMIZATIONCN = 268,
     DOROUTEOPTIMIZATIONMN = 269,
     HOMEADDRESS = 270,
     HOMEAGENTADDRESS = 271,
     INITIALBINDACKTIMEOUTFIRSTREG = 272,
     INITIALBINDACKTIMEOUTREREG = 273,
     LINKNAME = 274,
     HAMAXBINDINGLIFE = 275,
     MNMAXHABINDINGLIFE = 276,
     MNMAXCNBINDINGLIFE = 277,
     MAXMOBPFXADVINTERVAL = 278,
     MINMOBPFXADVINTERVAL = 279,
     MNHOMELINK = 280,
     HAHOMELINK = 281,
     NONVOLATILEBINDINGCACHE = 282,
     SENDMOBPFXSOLS = 283,
     SENDUNSOLMOBPFXADVS = 284,
     SENDMOBPFXADVS = 285,
     IPSECPOLICYSET = 286,
     IPSECPOLICY = 287,
     IPSECTYPE = 288,
     USEALTCOA = 289,
     USEESP = 290,
     USEAH = 291,
     USEIPCOMP = 292,
     BLOCK = 293,
     USEMNHAIPSEC = 294,
     KEYMNGMOBCAPABILITY = 295,
     HOMEREGBINDING = 296,
     MH = 297,
     MOBPFXDISC = 298,
     TUNNELHOMETESTING = 299,
     TUNNELMH = 300,
     TUNNELPAYLOAD = 301,
     USEMOVEMENTMODULE = 302,
     USEPOLICYMODULE = 303,
     MIP6CN = 304,
     MIP6MN = 305,
     MIP6HA = 306,
     INTERNAL = 307,
     MNROPOLICY = 308,
     ICMP = 309,
     ANY = 310,
     DOROUTEOPT = 311,
     DEFAULTBINDINGACLPOLICY = 312,
     BINDINGACLPOLICY = 313,
     MNADDRESS = 314,
     USECNBUACK = 315,
     INTERFACE = 316,
     IFNAME = 317,
     IFTYPE = 318,
     MNIFPREFERENCE = 319,
     MNUSEALLINTERFACES = 320,
     MNROUTERPROBES = 321,
     MNROUTERPROBETIMEOUT = 322,
     MNDISCARDHAPARAMPROB = 323,
     OPTIMISTICHANDOFF = 324,
     RFC5213TIMESTAMPBASEDAPPROACHINUSE = 325,
     RFC5213MOBILENODEGENERATEDTIMESTAMPINUSE = 326,
     RFC5213FIXEDMAGLINKLOCALADDRESSONALLACCESSLINKS = 327,
     RFC5213FIXEDMAGLINKLAYERADDRESSONALLACCESSLINKS = 328,
     RFC5213MINDELAYBEFOREBCEDELETE = 329,
     RFC5213MAXDELAYBEFORENEWBCEASSIGN = 330,
     RFC5213TIMESTAMPVALIDITYWINDOW = 331,
     RFC5213ENABLEMAGLOCALROUTING = 332,
     MIP6LMA = 333,
     MIP6MAG = 334,
     PROXYMIPLMA = 335,
     PROXYMIPMAG = 336,
     ALLLMAMULTICASTADDRESS = 337,
     LMAADDRESS = 338,
     LMAPMIPNETWORKDEVICE = 339,
     LMACORENETWORKADDRESS = 340,
     LMACORENETWORKDEVICE = 341,
     MAGADDRESSINGRESS = 342,
     MAGADDRESSEGRESS = 343,
     MAG1ADDRESSINGRESS = 344,
     MAG1ADDRESSEGRESS = 345,
     MAG2ADDRESSINGRESS = 346,
     MAG2ADDRESSEGRESS = 347,
     MAG3ADDRESSINGRESS = 348,
     MAG3ADDRESSEGRESS = 349,
     MAGDEVICEINGRESS = 350,
     MAGDEVICEEGRESS = 351,
     OURADDRESS = 352,
     HOMENETWORKPREFIX = 353,
     PBULIFETIME = 354,
     PBALIFETIME = 355,
     RETRANSMISSIONTIMEOUT = 356,
     MAXMESSAGERETRANSMISSIONS = 357,
     TUNNELINGENABLED = 358,
     DYNAMICTUNNELINGENABLED = 359,
     RADIUSPASSWORD = 360,
     RADIUSCLIENTCONFIGFILE = 361,
     PCAPSYSLOGASSOCIATIONGREPSTRING = 362,
     PCAPSYSLOGDEASSOCIATIONGREPSTRING = 363,
     INV_TOKEN = 364
   };
#endif
/* Tokens.  */
#define QSTRING 258
#define ADDR 259
#define MACADDR 260
#define BOOL 261
#define NUMBER 262
#define DECIMAL 263
#define NUMPAIR 264
#define MIP6ENTITY 265
#define DEBUGLEVEL 266
#define DEBUGLOGFILE 267
#define DOROUTEOPTIMIZATIONCN 268
#define DOROUTEOPTIMIZATIONMN 269
#define HOMEADDRESS 270
#define HOMEAGENTADDRESS 271
#define INITIALBINDACKTIMEOUTFIRSTREG 272
#define INITIALBINDACKTIMEOUTREREG 273
#define LINKNAME 274
#define HAMAXBINDINGLIFE 275
#define MNMAXHABINDINGLIFE 276
#define MNMAXCNBINDINGLIFE 277
#define MAXMOBPFXADVINTERVAL 278
#define MINMOBPFXADVINTERVAL 279
#define MNHOMELINK 280
#define HAHOMELINK 281
#define NONVOLATILEBINDINGCACHE 282
#define SENDMOBPFXSOLS 283
#define SENDUNSOLMOBPFXADVS 284
#define SENDMOBPFXADVS 285
#define IPSECPOLICYSET 286
#define IPSECPOLICY 287
#define IPSECTYPE 288
#define USEALTCOA 289
#define USEESP 290
#define USEAH 291
#define USEIPCOMP 292
#define BLOCK 293
#define USEMNHAIPSEC 294
#define KEYMNGMOBCAPABILITY 295
#define HOMEREGBINDING 296
#define MH 297
#define MOBPFXDISC 298
#define TUNNELHOMETESTING 299
#define TUNNELMH 300
#define TUNNELPAYLOAD 301
#define USEMOVEMENTMODULE 302
#define USEPOLICYMODULE 303
#define MIP6CN 304
#define MIP6MN 305
#define MIP6HA 306
#define INTERNAL 307
#define MNROPOLICY 308
#define ICMP 309
#define ANY 310
#define DOROUTEOPT 311
#define DEFAULTBINDINGACLPOLICY 312
#define BINDINGACLPOLICY 313
#define MNADDRESS 314
#define USECNBUACK 315
#define INTERFACE 316
#define IFNAME 317
#define IFTYPE 318
#define MNIFPREFERENCE 319
#define MNUSEALLINTERFACES 320
#define MNROUTERPROBES 321
#define MNROUTERPROBETIMEOUT 322
#define MNDISCARDHAPARAMPROB 323
#define OPTIMISTICHANDOFF 324
#define RFC5213TIMESTAMPBASEDAPPROACHINUSE 325
#define RFC5213MOBILENODEGENERATEDTIMESTAMPINUSE 326
#define RFC5213FIXEDMAGLINKLOCALADDRESSONALLACCESSLINKS 327
#define RFC5213FIXEDMAGLINKLAYERADDRESSONALLACCESSLINKS 328
#define RFC5213MINDELAYBEFOREBCEDELETE 329
#define RFC5213MAXDELAYBEFORENEWBCEASSIGN 330
#define RFC5213TIMESTAMPVALIDITYWINDOW 331
#define RFC5213ENABLEMAGLOCALROUTING 332
#define MIP6LMA 333
#define MIP6MAG 334
#define PROXYMIPLMA 335
#define PROXYMIPMAG 336
#define ALLLMAMULTICASTADDRESS 337
#define LMAADDRESS 338
#define LMAPMIPNETWORKDEVICE 339
#define LMACORENETWORKADDRESS 340
#define LMACORENETWORKDEVICE 341
#define MAGADDRESSINGRESS 342
#define MAGADDRESSEGRESS 343
#define MAG1ADDRESSINGRESS 344
#define MAG1ADDRESSEGRESS 345
#define MAG2ADDRESSINGRESS 346
#define MAG2ADDRESSEGRESS 347
#define MAG3ADDRESSINGRESS 348
#define MAG3ADDRESSEGRESS 349
#define MAGDEVICEINGRESS 350
#define MAGDEVICEEGRESS 351
#define OURADDRESS 352
#define HOMENETWORKPREFIX 353
#define PBULIFETIME 354
#define PBALIFETIME 355
#define RETRANSMISSIONTIMEOUT 356
#define MAXMESSAGERETRANSMISSIONS 357
#define TUNNELINGENABLED 358
#define DYNAMICTUNNELINGENABLED 359
#define RADIUSPASSWORD 360
#define RADIUSCLIENTCONFIGFILE 361
#define PCAPSYSLOGASSOCIATIONGREPSTRING 362
#define PCAPSYSLOGDEASSOCIATIONGREPSTRING 363
#define INV_TOKEN 364




#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED
typedef union YYSTYPE
{

/* Line 1676 of yacc.c  */
#line 111 "gram.y"

	char *string;
	struct in6_addr addr;
	struct in6_addr macaddr;
	char bool;
	unsigned int num;
	unsigned int numpair[2];
	double dec;



/* Line 1676 of yacc.c  */
#line 282 "gram.h"
} YYSTYPE;
# define YYSTYPE_IS_TRIVIAL 1
# define yystype YYSTYPE /* obsolescent; will be withdrawn */
# define YYSTYPE_IS_DECLARED 1
#endif

extern YYSTYPE yylval;


