CC= gcc
CFLAGS = -I/usr/include/libxml2
LIB = -lxml2

OCG:
	${CC} ${CFLAGS} ${LIB} OCG.c OCG_get_opt.c OCG_detect_file.c OCG_parse_filename.c OCG_create_dir.c OCG_parse_XML.c OCG_save_XML.c OCG_config_mobi.c OCG_generate_report.c -o OCG

	 
