CC= gcc
CFLAGS = -I/usr/include/libxml2
LIB = -lxml2

OCG:
	${CC} ${CFLAGS} ${LIB} src/OCG.c src/OCG_get_opt.c src/OCG_detect_file.c src/OCG_parse_filename.c src/OCG_create_dir.c src/OCG_parse_XML.c src/OCG_save_XML.c src/OCG_call_emu.c src/OCG_config_mobi.c src/OCG_generate_report.c src/log.c -o OCG

	 
